# docker/docker-compose.yml
version: "3"

services:
  database:
    container_name: app-db
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/dump-db.sh:/dump-db.sh
      - ./database/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  php-fpm:
    container_name: app-php
    build:
      context: ./php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ../:/var/www
      - ./php-fpm/conf.d/php.ini:/usr/local/etc/php/php.ini
      - ./scripts/composer-install.sh:/composer-install.sh

  nginx:
    container_name: app-web
    depends_on:
      - php-fpm
    build:
      context: ./nginx
    ports:
      - "${WWW_PORT}:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
      - ./scripts/watch-theme.sh:/watch-theme.sh